package cn.cleancoder.springboot.sql.mapper;

import org.apache.ibatis.annotations.Mapper;

import cn.cleancoder.springboot.sql.model.Card;

@Mapper
public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    Card selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int updateByPrimaryKey(Card record);
}