package cn.cleancoder.springboot.sql.mapper;

import cn.cleancoder.springboot.sql.model.TodoList;
import cn.cleancoder.springboot.sql.model.TodoListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodoListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    long countByExample(TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int deleteByExample(TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int insert(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int insertSelective(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    List<TodoList> selectByExample(TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    TodoList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") TodoList record, @Param("example") TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int updateByExample(@Param("record") TodoList record, @Param("example") TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int updateByPrimaryKeySelective(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo_list
     *
     * @mbg.generated Thu Aug 23 11:36:13 CST 2018
     */
    int updateByPrimaryKey(TodoList record);
}