package cn.cleancoder.springboot.sql.model;

public class Card {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.title
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.todo_list_id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    private Integer todoListId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.id
     *
     * @return the value of t_card.id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.id
     *
     * @param id the value for t_card.id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.title
     *
     * @return the value of t_card.title
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.title
     *
     * @param title the value for t_card.title
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.todo_list_id
     *
     * @return the value of t_card.todo_list_id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public Integer getTodoListId() {
        return todoListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.todo_list_id
     *
     * @param todoListId the value for t_card.todo_list_id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public void setTodoListId(Integer todoListId) {
        this.todoListId = todoListId;
    }
}