package cn.cleancoder.springboot.sql.model;

public class TodoList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo_list.id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo_list.title
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo_list.board_id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    private Integer boardId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo_list.id
     *
     * @return the value of t_todo_list.id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo_list.id
     *
     * @param id the value for t_todo_list.id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo_list.title
     *
     * @return the value of t_todo_list.title
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo_list.title
     *
     * @param title the value for t_todo_list.title
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo_list.board_id
     *
     * @return the value of t_todo_list.board_id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo_list.board_id
     *
     * @param boardId the value for t_todo_list.board_id
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }
}