package cn.cleancoder.springboot.sql.dao;

import cn.cleancoder.springboot.sql.model.Card;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    Card selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Thu Aug 23 23:10:10 CST 2018
     */
    int updateByPrimaryKey(Card record);
}